export type SDLTRegion = "england" | "scotland" | "wales" | "northern_ireland";

export interface CityNeighbourhood {
  name: string;
  avg: number;
  vibe: string;
}

export interface CityData {
  name: string;
  slug: string;
  region: string;
  sdltRegion: SDLTRegion;
  avgHousePrice: number;
  avgPrice: number;
  ftbPrice: number;
  avgDeposit: number;
  monthlySearches: number;
  description: string;
  intro: string;
  taxName: string;
  yoyChange: number;
  rentMonthly: number;
  neighbourhoods: CityNeighbourhood[];
}

export const cities: CityData[] = [
  { name: "London", slug: "london", region: "Greater London", sdltRegion: "england", avgHousePrice: 523000, avgPrice: 523000, ftbPrice: 350000, avgDeposit: 52300, monthlySearches: 8100, yoyChange: 1.8, rentMonthly: 2400, description: "London has the UK's highest property prices, averaging around £523,000 in 2024.", intro: "London is the UK's most expensive property market, with prices averaging £523,000 across all boroughs.", taxName: "SDLT", neighbourhoods: [{ name: "Zone 1-2", avg: 750000, vibe: "Premium central living" }, { name: "Zone 3-4", avg: 480000, vibe: "Commuter sweet spot" }, { name: "Zone 5-6", avg: 360000, vibe: "Suburban value" }, { name: "East London", avg: 420000, vibe: "Regeneration growth" }] },
  { name: "Manchester", slug: "manchester", region: "North West England", sdltRegion: "england", avgHousePrice: 242000, avgPrice: 242000, ftbPrice: 195000, avgDeposit: 24200, monthlySearches: 2400, yoyChange: 3.2, rentMonthly: 1150, description: "Manchester has seen strong price growth, averaging around £242,000 in 2024.", intro: "Manchester is the North's powerhouse city, with strong price growth and a growing graduate population.", taxName: "SDLT", neighbourhoods: [{ name: "City Centre", avg: 320000, vibe: "Urban buzz, rental demand" }, { name: "Didsbury", avg: 380000, vibe: "Family-friendly, leafy" }, { name: "Salford Quays", avg: 240000, vibe: "MediaCity growth area" }, { name: "Stockport", avg: 210000, vibe: "Affordable commuter belt" }] },
  { name: "Birmingham", slug: "birmingham", region: "West Midlands", sdltRegion: "england", avgHousePrice: 232000, avgPrice: 232000, ftbPrice: 185000, avgDeposit: 23200, monthlySearches: 1900, yoyChange: 2.8, rentMonthly: 1050, description: "Birmingham is the UK's second city with average prices around £232,000.", intro: "Birmingham, the UK's second city, has benefited from the Commonwealth Games legacy and HS2 investment.", taxName: "SDLT", neighbourhoods: [{ name: "Edgbaston", avg: 320000, vibe: "Upmarket, professional" }, { name: "Moseley", avg: 280000, vibe: "Bohemian village feel" }, { name: "Solihull", avg: 350000, vibe: "Affluent commuter town" }, { name: "Digbeth", avg: 210000, vibe: "Creative quarter" }] },
  { name: "Bristol", slug: "bristol", region: "South West England", sdltRegion: "england", avgHousePrice: 363000, avgPrice: 363000, ftbPrice: 290000, avgDeposit: 36300, monthlySearches: 1600, yoyChange: 2.1, rentMonthly: 1600, description: "Bristol commands premium prices in the South West, averaging £363,000.", intro: "Bristol consistently ranks among the UK's most desirable cities, with a strong tech economy and lifestyle appeal.", taxName: "SDLT", neighbourhoods: [{ name: "Clifton", avg: 520000, vibe: "Iconic Georgian architecture" }, { name: "Southville", avg: 380000, vibe: "Trendy, young professional" }, { name: "Fishponds", avg: 290000, vibe: "Affordable east Bristol" }, { name: "Filton", avg: 310000, vibe: "Aerospace corridor" }] },
  { name: "Leeds", slug: "leeds-city", region: "Yorkshire", sdltRegion: "england", avgHousePrice: 231000, avgPrice: 231000, ftbPrice: 185000, avgDeposit: 23100, monthlySearches: 1500, yoyChange: 2.9, rentMonthly: 1000, description: "Leeds offers good value in Yorkshire with average prices of £231,000.", intro: "Leeds is Yorkshire's financial capital, with a diverse economy and strong rental market.", taxName: "SDLT", neighbourhoods: [{ name: "Headingley", avg: 280000, vibe: "Student and professional mix" }, { name: "Roundhay", avg: 370000, vibe: "Premium park-side living" }, { name: "Chapel Allerton", avg: 310000, vibe: "Vibrant village atmosphere" }, { name: "Pudsey", avg: 210000, vibe: "Affordable family area" }] },
  { name: "Edinburgh", slug: "edinburgh", region: "Scotland", sdltRegion: "scotland", avgHousePrice: 310000, avgPrice: 310000, ftbPrice: 245000, avgDeposit: 31000, monthlySearches: 1400, yoyChange: 3.5, rentMonthly: 1450, description: "Edinburgh is Scotland's most expensive city, averaging £310,000.", intro: "Edinburgh combines world-class culture, a thriving finance sector and stunning architecture.", taxName: "LBTT", neighbourhoods: [{ name: "New Town", avg: 480000, vibe: "Georgian grandeur" }, { name: "Leith", avg: 280000, vibe: "Waterfront regeneration" }, { name: "Morningside", avg: 420000, vibe: "Upmarket family area" }, { name: "Bruntsfield", avg: 390000, vibe: "Trendy, park-side" }] },
  { name: "Sheffield", slug: "sheffield", region: "Yorkshire", sdltRegion: "england", avgHousePrice: 194000, avgPrice: 194000, ftbPrice: 155000, avgDeposit: 19400, monthlySearches: 900, yoyChange: 2.6, rentMonthly: 850, description: "Sheffield offers affordable options in Yorkshire, averaging around £194,000.", intro: "Sheffield offers excellent value in the North, with strong university ties and a green city reputation.", taxName: "SDLT", neighbourhoods: [{ name: "Crookes", avg: 230000, vibe: "Popular student area" }, { name: "Fulwood", avg: 320000, vibe: "Leafy western suburb" }, { name: "Kelham Island", avg: 220000, vibe: "Industrial-chic regeneration" }, { name: "Hillsborough", avg: 160000, vibe: "Affordable north-west" }] },
  { name: "Liverpool", slug: "liverpool", region: "North West England", sdltRegion: "england", avgHousePrice: 190000, avgPrice: 190000, ftbPrice: 155000, avgDeposit: 19000, monthlySearches: 950, yoyChange: 3.8, rentMonthly: 850, description: "Liverpool has competitive city-centre prices averaging around £190,000.", intro: "Liverpool offers some of the best rental yields in England, with a huge regeneration programme transforming the waterfront.", taxName: "SDLT", neighbourhoods: [{ name: "Woolton", avg: 290000, vibe: "Leafy village feel" }, { name: "Aigburth", avg: 250000, vibe: "Riverside family area" }, { name: "Anfield", avg: 120000, vibe: "Regeneration investment" }, { name: "Baltic Triangle", avg: 200000, vibe: "Creative quarter" }] },
  { name: "Newcastle", slug: "newcastle-city", region: "North East England", sdltRegion: "england", avgHousePrice: 172000, avgPrice: 172000, ftbPrice: 140000, avgDeposit: 17200, monthlySearches: 750, yoyChange: 2.4, rentMonthly: 800, description: "Newcastle upon Tyne offers great value in the North East, averaging £172,000.", intro: "Newcastle is one of England's most affordable major cities, with a vibrant cultural scene and strong rental demand.", taxName: "SDLT", neighbourhoods: [{ name: "Jesmond", avg: 260000, vibe: "Student and professional" }, { name: "Gosforth", avg: 290000, vibe: "Affluent suburb" }, { name: "Gateshead Quayside", avg: 200000, vibe: "Regeneration riverside" }, { name: "Heaton", avg: 180000, vibe: "Up-and-coming east" }] },
  { name: "Glasgow", slug: "glasgow", region: "Scotland", sdltRegion: "scotland", avgHousePrice: 185000, avgPrice: 185000, ftbPrice: 150000, avgDeposit: 18500, monthlySearches: 1100, yoyChange: 4.1, rentMonthly: 900, description: "Glasgow is Scotland's largest city with average prices of £185,000.", intro: "Glasgow is Scotland's largest city and most affordable major market, with one of the fastest-growing rental markets in the UK.", taxName: "LBTT", neighbourhoods: [{ name: "West End", avg: 280000, vibe: "Culture and university hub" }, { name: "Merchant City", avg: 220000, vibe: "Trendy city centre" }, { name: "Shawlands", avg: 210000, vibe: "South-side village" }, { name: "Partick", avg: 230000, vibe: "Young professional favourite" }] },
  { name: "Cardiff", slug: "cardiff", region: "Wales", sdltRegion: "wales", avgHousePrice: 248000, avgPrice: 248000, ftbPrice: 200000, avgDeposit: 24800, monthlySearches: 850, yoyChange: 2.5, rentMonthly: 1100, description: "Cardiff is the Welsh capital with average property prices around £248,000.", intro: "Cardiff is Wales' thriving capital, with a growing tech and media sector driving demand and Land Transaction Tax replacing stamp duty.", taxName: "LTT", neighbourhoods: [{ name: "Pontcanna", avg: 380000, vibe: "Leafy and upmarket" }, { name: "Roath", avg: 250000, vibe: "Victorian terraces, popular" }, { name: "Cardiff Bay", avg: 280000, vibe: "Waterfront regeneration" }, { name: "Cathays", avg: 220000, vibe: "Student and young professional" }] },
  { name: "Nottingham", slug: "nottingham-city", region: "East Midlands", sdltRegion: "england", avgHousePrice: 202000, avgPrice: 202000, ftbPrice: 165000, avgDeposit: 20200, monthlySearches: 700, yoyChange: 2.3, rentMonthly: 900, description: "Nottingham offers good value in the East Midlands, averaging £202,000.", intro: "Nottingham punches above its weight with two universities, a strong tech scene and average prices well below the national average.", taxName: "SDLT", neighbourhoods: [{ name: "The Park", avg: 480000, vibe: "Prestigious conservation area" }, { name: "West Bridgford", avg: 330000, vibe: "Families and professionals" }, { name: "Sherwood", avg: 210000, vibe: "Popular, good transport" }, { name: "Beeston", avg: 230000, vibe: "University quarter" }] },
  { name: "Leicester", slug: "leicester", region: "East Midlands", sdltRegion: "england", avgHousePrice: 216000, avgPrice: 216000, ftbPrice: 175000, avgDeposit: 21600, monthlySearches: 650, yoyChange: 2.7, rentMonthly: 950, description: "Leicester is a growing Midlands city with average prices of £216,000.", intro: "Leicester is a diverse, affordable Midlands city with a rich industrial heritage and strong value for money.", taxName: "SDLT", neighbourhoods: [{ name: "Stoneygate", avg: 320000, vibe: "Victorian villa country" }, { name: "Oadby", avg: 290000, vibe: "Affluent suburb" }, { name: "Clarendon Park", avg: 250000, vibe: "Young professional" }, { name: "Evington", avg: 190000, vibe: "Multicultural, affordable" }] },
  { name: "Bradford", slug: "bradford", region: "Yorkshire", sdltRegion: "england", avgHousePrice: 158000, avgPrice: 158000, ftbPrice: 125000, avgDeposit: 15800, monthlySearches: 500, yoyChange: 3.1, rentMonthly: 700, description: "Bradford is one of the most affordable cities in Yorkshire, averaging £158,000.", intro: "Bradford is one of the UK's most affordable major cities, with UK City of Culture 2025 status driving new investment.", taxName: "SDLT", neighbourhoods: [{ name: "Ilkley", avg: 380000, vibe: "Premium spa town" }, { name: "Shipley", avg: 200000, vibe: "Canal-side, improving" }, { name: "Bingley", avg: 220000, vibe: "Leafy Aire valley" }, { name: "Keighley", avg: 150000, vibe: "Budget-friendly" }] },
  { name: "Southampton", slug: "southampton", region: "South East England", sdltRegion: "england", avgHousePrice: 267000, avgPrice: 267000, ftbPrice: 215000, avgDeposit: 26700, monthlySearches: 600, yoyChange: 1.9, rentMonthly: 1150, description: "Southampton averages £267,000 on the South Coast.", intro: "Southampton is a major port city on the South Coast with two universities and strong employment links.", taxName: "SDLT", neighbourhoods: [{ name: "Bitterne", avg: 280000, vibe: "Popular family area" }, { name: "Shirley", avg: 240000, vibe: "Central and accessible" }, { name: "Hamble", avg: 360000, vibe: "Riverside village premium" }, { name: "Woolston", avg: 220000, vibe: "Affordable east side" }] },
  { name: "Portsmouth", slug: "portsmouth", region: "South East England", sdltRegion: "england", avgHousePrice: 255000, avgPrice: 255000, ftbPrice: 205000, avgDeposit: 25500, monthlySearches: 500, yoyChange: 1.8, rentMonthly: 1100, description: "Portsmouth is an island city with average prices around £255,000.", intro: "Portsmouth is Britain's only island city, with a strong naval heritage, Gunwharf Quays and average prices of £255,000.", taxName: "SDLT", neighbourhoods: [{ name: "Southsea", avg: 290000, vibe: "Seafront lifestyle" }, { name: "Cosham", avg: 230000, vibe: "Affordable northern area" }, { name: "Old Portsmouth", avg: 310000, vibe: "Historic waterfront" }, { name: "Fratton", avg: 210000, vibe: "Most affordable" }] },
  { name: "Oxford", slug: "oxford", region: "South East England", sdltRegion: "england", avgHousePrice: 471000, avgPrice: 471000, ftbPrice: 370000, avgDeposit: 47100, monthlySearches: 900, yoyChange: 1.4, rentMonthly: 2000, description: "Oxford commands high prices due to university demand, averaging £471,000.", intro: "Oxford's world-renowned university, strong tech sector and Green Belt constraints have pushed average prices to £471,000.", taxName: "SDLT", neighbourhoods: [{ name: "Summertown", avg: 620000, vibe: "North Oxford premium" }, { name: "Jericho", avg: 550000, vibe: "Bohemian, central" }, { name: "Cowley", avg: 380000, vibe: "More affordable east" }, { name: "Headington", avg: 430000, vibe: "Hospital and university area" }] },
  { name: "Cambridge", slug: "cambridge-city", region: "East of England", sdltRegion: "england", avgHousePrice: 497000, avgPrice: 497000, ftbPrice: 390000, avgDeposit: 49700, monthlySearches: 950, yoyChange: 1.2, rentMonthly: 2100, description: "Cambridge has seen exceptional growth, averaging £497,000 in 2024.", intro: "Cambridge's Silicon Fen tech cluster and world-famous university have driven prices to £497,000.", taxName: "SDLT", neighbourhoods: [{ name: "Newnham", avg: 680000, vibe: "Academic excellence area" }, { name: "Romsey", avg: 450000, vibe: "Victorian terraces" }, { name: "Cherry Hinton", avg: 390000, vibe: "More accessible south" }, { name: "Chesterton", avg: 480000, vibe: "North Cambridge, popular" }] },
  { name: "Brighton", slug: "brighton", region: "South East England", sdltRegion: "england", avgHousePrice: 393000, avgPrice: 393000, ftbPrice: 315000, avgDeposit: 39300, monthlySearches: 900, yoyChange: 1.6, rentMonthly: 1750, description: "Brighton is a highly desirable coastal city averaging £393,000.", intro: "Brighton blends seaside lifestyle with London commuter appeal, pushing prices to £393,000.", taxName: "SDLT", neighbourhoods: [{ name: "Hove Park", avg: 520000, vibe: "Family premium" }, { name: "North Laine", avg: 380000, vibe: "Bohemian city centre" }, { name: "Kemp Town", avg: 350000, vibe: "Seaside, vibrant" }, { name: "Portslade", avg: 290000, vibe: "Affordable western edge" }] },
  { name: "Reading", slug: "reading", region: "South East England", sdltRegion: "england", avgHousePrice: 365000, avgPrice: 365000, ftbPrice: 290000, avgDeposit: 36500, monthlySearches: 700, yoyChange: 1.8, rentMonthly: 1600, description: "Reading is a key commuter hub west of London, averaging £365,000.", intro: "Reading is the UK's tech capital outside London, with Oracle, Microsoft and Vodafone HQs driving housing demand.", taxName: "SDLT", neighbourhoods: [{ name: "Caversham", avg: 450000, vibe: "Thames-side premium" }, { name: "Earley", avg: 380000, vibe: "Family-friendly east" }, { name: "Reading Town", avg: 320000, vibe: "Central urban" }, { name: "Tilehurst", avg: 340000, vibe: "Western suburbs" }] },
  { name: "Milton Keynes", slug: "milton-keynes", region: "South East England", sdltRegion: "england", avgHousePrice: 298000, avgPrice: 298000, ftbPrice: 238000, avgDeposit: 29800, monthlySearches: 550, yoyChange: 2.1, rentMonthly: 1250, description: "Milton Keynes is a well-connected planned city averaging £298,000.", intro: "Milton Keynes is the UK's fastest-growing city, with tech investment, low crime and excellent transport links.", taxName: "SDLT", neighbourhoods: [{ name: "Woburn Sands", avg: 390000, vibe: "Village charm, commutable" }, { name: "Newport Pagnell", avg: 320000, vibe: "Market town feel" }, { name: "Bletchley", avg: 250000, vibe: "Most affordable area" }, { name: "Central MK", avg: 280000, vibe: "Urban living, regenerating" }] },
  { name: "Derby", slug: "derby", region: "East Midlands", sdltRegion: "england", avgHousePrice: 196000, avgPrice: 196000, ftbPrice: 158000, avgDeposit: 19600, monthlySearches: 500, yoyChange: 2.4, rentMonthly: 850, description: "Derby is an industrial city in the East Midlands averaging £196,000.", intro: "Derby is the Midlands' manufacturing heart, home to Rolls-Royce and Toyota, with average prices of £196,000.", taxName: "SDLT", neighbourhoods: [{ name: "Mickleover", avg: 280000, vibe: "Affluent western suburb" }, { name: "Allestree", avg: 260000, vibe: "Family north side" }, { name: "Littleover", avg: 270000, vibe: "Popular south" }, { name: "Normanton", avg: 150000, vibe: "Most affordable area" }] },
  { name: "Stoke-on-Trent", slug: "stoke", region: "West Midlands", sdltRegion: "england", avgHousePrice: 149000, avgPrice: 149000, ftbPrice: 120000, avgDeposit: 14900, monthlySearches: 450, yoyChange: 3.3, rentMonthly: 650, description: "Stoke-on-Trent is one of England's most affordable cities at £149,000 average.", intro: "Stoke-on-Trent offers exceptional value at £149,000 average, with strong rental yields attracting investors.", taxName: "SDLT", neighbourhoods: [{ name: "Trentham", avg: 250000, vibe: "Premium south Stoke" }, { name: "Hartshill", avg: 190000, vibe: "Hospital quarter" }, { name: "Burslem", avg: 120000, vibe: "Pottery heartland" }, { name: "Fenton", avg: 130000, vibe: "Most affordable" }] },
  { name: "Plymouth", slug: "plymouth", region: "South West England", sdltRegion: "england", avgHousePrice: 228000, avgPrice: 228000, ftbPrice: 182000, avgDeposit: 22800, monthlySearches: 500, yoyChange: 2.0, rentMonthly: 950, description: "Plymouth is a naval city in Devon with average prices around £228,000.", intro: "Plymouth is Britain's Ocean City, a naval base, university town and tourism hub with strong seaside lifestyle appeal.", taxName: "SDLT", neighbourhoods: [{ name: "Plymstock", avg: 280000, vibe: "Coastal family suburb" }, { name: "Mannamead", avg: 300000, vibe: "Professional central" }, { name: "Devonport", avg: 160000, vibe: "Naval quarter, improving" }, { name: "Mutley", avg: 200000, vibe: "Student area" }] },
  { name: "Sunderland", slug: "sunderland", region: "North East England", sdltRegion: "england", avgHousePrice: 143000, avgPrice: 143000, ftbPrice: 115000, avgDeposit: 14300, monthlySearches: 400, yoyChange: 2.6, rentMonthly: 650, description: "Sunderland is one of the UK's most affordable cities at around £143,000 average.", intro: "Sunderland offers some of the UK's best value property, with a regenerating city centre and waterfront development.", taxName: "SDLT", neighbourhoods: [{ name: "Cleadon", avg: 240000, vibe: "Village, commutable" }, { name: "Seaburn", avg: 190000, vibe: "Coastal north side" }, { name: "Hendon", avg: 100000, vibe: "Affordable regeneration" }, { name: "Ryhope", avg: 155000, vibe: "Former pit village" }] },
  { name: "Exeter", slug: "exeter", region: "South West England", sdltRegion: "england", avgHousePrice: 320000, avgPrice: 320000, ftbPrice: 255000, avgDeposit: 32000, monthlySearches: 500, yoyChange: 2.0, rentMonthly: 1350, description: "Exeter is a thriving university city in Devon averaging £320,000.", intro: "Exeter is the South West's fastest-growing economy, with a Russell Group university and strong business services sector.", taxName: "SDLT", neighbourhoods: [{ name: "St Leonard's", avg: 420000, vibe: "Victorian premium" }, { name: "Heavitree", avg: 280000, vibe: "Student-popular east" }, { name: "Pinhoe", avg: 300000, vibe: "Family suburb" }, { name: "Exwick", avg: 260000, vibe: "Affordable western edge" }] },
  { name: "York", slug: "york", region: "Yorkshire", sdltRegion: "england", avgHousePrice: 333000, avgPrice: 333000, ftbPrice: 265000, avgDeposit: 33300, monthlySearches: 600, yoyChange: 2.2, rentMonthly: 1300, description: "York is one of England's most desirable historic cities, averaging £333,000.", intro: "York is England's most-visited historic city, with high tourism and a supply-constrained market pushing average prices to £333,000.", taxName: "SDLT", neighbourhoods: [{ name: "Bishopthorpe", avg: 420000, vibe: "Village adjacent to city" }, { name: "Heslington", avg: 360000, vibe: "University area" }, { name: "Acomb", avg: 250000, vibe: "Affordable western suburb" }, { name: "Huntington", avg: 290000, vibe: "Popular northern area" }] },
  { name: "Bournemouth", slug: "bournemouth", region: "South West England", sdltRegion: "england", avgHousePrice: 335000, avgPrice: 335000, ftbPrice: 265000, avgDeposit: 33500, monthlySearches: 550, yoyChange: 1.7, rentMonthly: 1400, description: "Bournemouth is a coastal resort town averaging £335,000.", intro: "Bournemouth offers a premium coastal lifestyle and consistently rated one of the UK's best beaches, driving prices to £335,000.", taxName: "SDLT", neighbourhoods: [{ name: "Sandbanks area", avg: 520000, vibe: "Britain's most expensive beach" }, { name: "Southbourne", avg: 350000, vibe: "Family beachside" }, { name: "Winton", avg: 270000, vibe: "Affordable inland" }, { name: "Charminster", avg: 290000, vibe: "Student and young prof" }] },
  { name: "Aberdeen", slug: "aberdeen", region: "Scotland", sdltRegion: "scotland", avgHousePrice: 183000, avgPrice: 183000, ftbPrice: 148000, avgDeposit: 18300, monthlySearches: 550, yoyChange: 0.8, rentMonthly: 850, description: "Aberdeen is Scotland's oil capital with average prices of £183,000.", intro: "Aberdeen is Scotland's energy capital, currently benefiting from the energy transition as prices average £183,000.", taxName: "LBTT", neighbourhoods: [{ name: "West End", avg: 260000, vibe: "Traditional granite city" }, { name: "Cults", avg: 320000, vibe: "Affluent western suburb" }, { name: "Torry", avg: 140000, vibe: "Affordable, improving" }, { name: "Bridge of Don", avg: 190000, vibe: "Modern northern suburb" }] },
  { name: "Belfast", slug: "belfast", region: "Northern Ireland", sdltRegion: "northern_ireland", avgHousePrice: 195000, avgPrice: 195000, ftbPrice: 160000, avgDeposit: 19500, monthlySearches: 700, yoyChange: 4.2, rentMonthly: 900, description: "Belfast is the capital of Northern Ireland with average prices around £195,000.", intro: "Belfast has seen the UK's strongest price growth, with fintech investment, film production and a young population driving prices to £195,000.", taxName: "SDLT", neighbourhoods: [{ name: "South Belfast", avg: 280000, vibe: "Professionals and students" }, { name: "Lisburn Road", avg: 320000, vibe: "Upmarket retail corridor" }, { name: "East Belfast", avg: 175000, vibe: "Affordable, regenerating" }, { name: "North Down", avg: 230000, vibe: "Coastal commuter" }] },
  { name: "Bath", slug: "bath-city", region: "South West England", sdltRegion: "england", avgHousePrice: 431000, avgPrice: 431000, ftbPrice: 340000, avgDeposit: 43100, monthlySearches: 500, yoyChange: 1.5, rentMonthly: 1800, description: "Bath is a UNESCO World Heritage city with average prices of £431,000.", intro: "Bath is a UNESCO World Heritage Site with unmatched architectural beauty, with prices driven to £431,000 by tourism and London overspill.", taxName: "SDLT", neighbourhoods: [{ name: "Lansdown", avg: 580000, vibe: "Premium Georgian hilltop" }, { name: "Widcombe", avg: 420000, vibe: "Village-in-the-city" }, { name: "Oldfield Park", avg: 350000, vibe: "Student and professional" }, { name: "Twerton", avg: 280000, vibe: "Most affordable area" }] },
  { name: "Guildford", slug: "guildford", region: "South East England", sdltRegion: "england", avgHousePrice: 498000, avgPrice: 498000, ftbPrice: 390000, avgDeposit: 49800, monthlySearches: 550, yoyChange: 1.3, rentMonthly: 2100, description: "Guildford is a premium Surrey commuter town averaging £498,000.", intro: "Guildford is one of the Home Counties' most prestigious addresses, with excellent schools and a fast London commute.", taxName: "SDLT", neighbourhoods: [{ name: "The Mount", avg: 680000, vibe: "Millionaires' row" }, { name: "Merrow", avg: 520000, vibe: "Leafy family suburb" }, { name: "Onslow Village", avg: 580000, vibe: "Exclusive estate" }, { name: "Park Barn", avg: 370000, vibe: "More affordable west" }] },
  { name: "Cheltenham", slug: "cheltenham", region: "South West England", sdltRegion: "england", avgHousePrice: 355000, avgPrice: 355000, ftbPrice: 280000, avgDeposit: 35500, monthlySearches: 450, yoyChange: 1.8, rentMonthly: 1450, description: "Cheltenham is an affluent Regency town in Gloucestershire averaging £355,000.", intro: "Cheltenham is a Regency gem with GCHQ, excellent schools and the famous festival circuit.", taxName: "SDLT", neighbourhoods: [{ name: "Montpellier", avg: 480000, vibe: "Elegant Regency core" }, { name: "Charlton Kings", avg: 420000, vibe: "Family-friendly village" }, { name: "Leckhampton", avg: 400000, vibe: "Sought-after south" }, { name: "Hesters Way", avg: 240000, vibe: "Affordable west" }] },
  { name: "Peterborough", slug: "peterborough", region: "East of England", sdltRegion: "england", avgHousePrice: 236000, avgPrice: 236000, ftbPrice: 190000, avgDeposit: 23600, monthlySearches: 400, yoyChange: 2.9, rentMonthly: 1000, description: "Peterborough offers good value in the East of England, averaging £236,000.", intro: "Peterborough is one of England's fastest-growing cities, with excellent rail links to London and Cambridge.", taxName: "SDLT", neighbourhoods: [{ name: "Hampton", avg: 280000, vibe: "Modern development, family" }, { name: "Longthorpe", avg: 310000, vibe: "Western premium" }, { name: "Dogsthorpe", avg: 190000, vibe: "Affordable north" }, { name: "Werrington", avg: 220000, vibe: "Northern suburb" }] },
  { name: "Norwich", slug: "norwich", region: "East of England", sdltRegion: "england", avgHousePrice: 261000, avgPrice: 261000, ftbPrice: 210000, avgDeposit: 26100, monthlySearches: 450, yoyChange: 2.3, rentMonthly: 1100, description: "Norwich is East Anglia's main city, with average property prices of £261,000.", intro: "Norwich is East Anglia's cultural capital, with a medieval city centre and two universities.", taxName: "SDLT", neighbourhoods: [{ name: "Golden Triangle", avg: 340000, vibe: "Professional, popular" }, { name: "Eaton", avg: 360000, vibe: "Leafy south side" }, { name: "Catton", avg: 230000, vibe: "Affordable north" }, { name: "Thorpe St Andrew", avg: 310000, vibe: "Riverside east" }] },
  { name: "Swansea", slug: "swansea", region: "Wales", sdltRegion: "wales", avgHousePrice: 196000, avgPrice: 196000, ftbPrice: 160000, avgDeposit: 19600, monthlySearches: 450, yoyChange: 3.1, rentMonthly: 850, description: "Swansea is Wales' second city with average prices around £196,000.", intro: "Swansea is Wales' second city with stunning bay views, a growing tech sector and Land Transaction Tax.", taxName: "LTT", neighbourhoods: [{ name: "Mumbles", avg: 320000, vibe: "Seaside village premium" }, { name: "Uplands", avg: 220000, vibe: "Student and young professional" }, { name: "SA1 Waterfront", avg: 240000, vibe: "Regeneration marina" }, { name: "Morriston", avg: 160000, vibe: "Affordable north" }] },
  { name: "Wolverhampton", slug: "wolverhampton", region: "West Midlands", sdltRegion: "england", avgHousePrice: 187000, avgPrice: 187000, ftbPrice: 150000, avgDeposit: 18700, monthlySearches: 450, yoyChange: 2.5, rentMonthly: 800, description: "Wolverhampton offers competitive West Midlands prices averaging £187,000.", intro: "Wolverhampton is an affordable West Midlands hub undergoing significant regeneration, with HS2 Interchange nearby.", taxName: "SDLT", neighbourhoods: [{ name: "Tettenhall", avg: 280000, vibe: "Upmarket western village" }, { name: "Penn", avg: 240000, vibe: "Suburban family area" }, { name: "Wednesfield", avg: 160000, vibe: "Affordable east" }, { name: "Wombourne", avg: 220000, vibe: "Rural fringe village" }] },
  { name: "Dundee", slug: "dundee", region: "Scotland", sdltRegion: "scotland", avgHousePrice: 163000, avgPrice: 163000, ftbPrice: 130000, avgDeposit: 16300, monthlySearches: 400, yoyChange: 4.5, rentMonthly: 750, description: "Dundee is a growing Scottish city with regeneration driving prices to £163,000.", intro: "Dundee is Scotland's fastest-growing city, transformed by the V&A Museum and waterfront regeneration.", taxName: "LBTT", neighbourhoods: [{ name: "West End", avg: 220000, vibe: "Upmarket, university adjacent" }, { name: "Broughty Ferry", avg: 270000, vibe: "Affluent coastal suburb" }, { name: "Lochee", avg: 130000, vibe: "Affordable west Dundee" }, { name: "Stobswell", avg: 150000, vibe: "City centre edge" }] },
  { name: "Luton", slug: "luton", region: "East of England", sdltRegion: "england", avgHousePrice: 295000, avgPrice: 295000, ftbPrice: 235000, avgDeposit: 29500, monthlySearches: 450, yoyChange: 1.6, rentMonthly: 1250, description: "Luton benefits from proximity to London, averaging around £295,000.", intro: "Luton is one of the best-value commuter towns for London workers, with direct trains to St Pancras in 22 minutes.", taxName: "SDLT", neighbourhoods: [{ name: "Harpenden", avg: 650000, vibe: "Premium commuter village" }, { name: "Stopsley", avg: 310000, vibe: "Suburban east Luton" }, { name: "Luton Town", avg: 250000, vibe: "Most central and affordable" }, { name: "Dunstable", avg: 290000, vibe: "Satellite town" }] },
  { name: "Northampton", slug: "northampton", region: "East Midlands", sdltRegion: "england", avgHousePrice: 241000, avgPrice: 241000, ftbPrice: 192000, avgDeposit: 24100, monthlySearches: 400, yoyChange: 2.6, rentMonthly: 1000, description: "Northampton is a growing town in the East Midlands averaging £241,000.", intro: "Northampton is one of England's fastest-growing towns, with HS2 proximity and excellent value for commuters.", taxName: "SDLT", neighbourhoods: [{ name: "Abington", avg: 300000, vibe: "Upmarket east side" }, { name: "Duston", avg: 250000, vibe: "Popular western suburb" }, { name: "Far Cotton", avg: 200000, vibe: "Affordable south" }, { name: "Kingsthorpe", avg: 270000, vibe: "Family north" }] },
];

export function getCityBySlug(slug: string): CityData | undefined {
  return cities.find((c) => c.slug === slug);
}

export const allCitySlugs: string[] = cities.map((c) => c.slug);
