export interface LenderData {
  name: string;
  slug: string;
  estimatedSvr: number;
  maxLtv: number;
  category: string;
  trustRating: number;
  description: string;
}

export const lenders: LenderData[] = [
  { name: "Lloyds Bank", slug: "lloyds-bank", estimatedSvr: 7.49, maxLtv: 95, category: "Big Six", trustRating: 5, description: "Lloyds Bank is one of the UK's largest mortgage lenders, offering a wide range of residential and buy-to-let products." },
  { name: "Halifax", slug: "halifax", estimatedSvr: 7.49, maxLtv: 95, category: "Big Six", trustRating: 5, description: "Halifax is the UK's largest mortgage lender by volume, known for competitive rates and first-time buyer support." },
  { name: "Nationwide Building Society", slug: "nationwide", estimatedSvr: 7.49, maxLtv: 95, category: "Big Six", trustRating: 5, description: "Nationwide is the world's largest building society, offering member-focused mortgage products and competitive rates." },
  { name: "Barclays", slug: "barclays", estimatedSvr: 7.49, maxLtv: 95, category: "Big Six", trustRating: 5, description: "Barclays offers a broad range of mortgage products including residential, remortgage, and buy-to-let options." },
  { name: "HSBC UK", slug: "hsbc", estimatedSvr: 6.99, maxLtv: 90, category: "Big Six", trustRating: 5, description: "HSBC UK provides competitive mortgage rates, particularly for existing customers and those with larger deposits." },
  { name: "NatWest", slug: "natwest", estimatedSvr: 7.49, maxLtv: 95, category: "Big Six", trustRating: 5, description: "NatWest offers a comprehensive range of mortgage products with strong digital tools and branch support." },
  { name: "Santander UK", slug: "santander", estimatedSvr: 7.5, maxLtv: 95, category: "Big Six", trustRating: 4, description: "Santander UK is a major mortgage lender with competitive products for home movers and remortgagors." },
  { name: "Virgin Money", slug: "virgin-money", estimatedSvr: 7.99, maxLtv: 95, category: "High Street", trustRating: 4, description: "Virgin Money offers innovative mortgage products with a focus on digital service and competitive fixed rates." },
  { name: "TSB Bank", slug: "tsb", estimatedSvr: 7.49, maxLtv: 95, category: "High Street", trustRating: 4, description: "TSB offers straightforward mortgage products for first-time buyers, home movers, and remortgagors." },
  { name: "Coventry Building Society", slug: "coventry", estimatedSvr: 7.2, maxLtv: 95, category: "Building Society", trustRating: 5, description: "Coventry Building Society consistently offers some of the UK's most competitive mortgage rates." },
  { name: "Yorkshire Building Society", slug: "yorkshire", estimatedSvr: 7.49, maxLtv: 95, category: "Building Society", trustRating: 4, description: "Yorkshire Building Society is the third-largest in the UK, known for value-focused mortgage products." },
  { name: "Skipton Building Society", slug: "skipton", estimatedSvr: 7.49, maxLtv: 100, category: "Building Society", trustRating: 4, description: "Skipton Building Society offers mortgages including its market-leading 100% Track Record Mortgage for renters." },
  { name: "Leeds Building Society", slug: "leeds", estimatedSvr: 7.49, maxLtv: 95, category: "Building Society", trustRating: 4, description: "Leeds Building Society provides member-focused mortgage products with strong service and competitive rates." },
  { name: "Principality Building Society", slug: "principality", estimatedSvr: 7.69, maxLtv: 95, category: "Building Society", trustRating: 4, description: "Principality Building Society is Wales' largest building society, serving Welsh and English borrowers." },
  { name: "Newcastle Building Society", slug: "newcastle", estimatedSvr: 7.49, maxLtv: 95, category: "Building Society", trustRating: 4, description: "Newcastle Building Society offers a range of residential mortgages with personal service." },
  { name: "Nottingham Building Society", slug: "nottingham", estimatedSvr: 7.99, maxLtv: 95, category: "Building Society", trustRating: 4, description: "Nottingham Building Society provides competitive mortgage products through brokers and its branch network." },
  { name: "West Bromwich Building Society", slug: "west-brom", estimatedSvr: 7.49, maxLtv: 95, category: "Building Society", trustRating: 4, description: "West Bromwich Building Society offers residential and buy-to-let mortgage products in the UK." },
  { name: "Cumberland Building Society", slug: "cumberland", estimatedSvr: 7.99, maxLtv: 95, category: "Building Society", trustRating: 4, description: "Cumberland Building Society serves the North of England and Scotland with competitive mortgage rates." },
  { name: "Suffolk Building Society", slug: "suffolk", estimatedSvr: 8.49, maxLtv: 80, category: "Building Society", trustRating: 3, description: "Suffolk Building Society offers bespoke mortgage products for complex and standard residential cases." },
  { name: "Cambridge Building Society", slug: "cambridge", estimatedSvr: 7.99, maxLtv: 90, category: "Building Society", trustRating: 3, description: "Cambridge Building Society provides personalised mortgage solutions for residential borrowers." },
  { name: "Bath Building Society", slug: "bath", estimatedSvr: 7.99, maxLtv: 80, category: "Building Society", trustRating: 3, description: "Bath Building Society offers specialist mortgage products including self-build and unusual properties." },
  { name: "Buckinghamshire Building Society", slug: "bucks", estimatedSvr: 8.49, maxLtv: 80, category: "Building Society", trustRating: 3, description: "Buckinghamshire Building Society provides flexible mortgage products for residential borrowers." },
  { name: "Dudley Building Society", slug: "dudley", estimatedSvr: 8.49, maxLtv: 80, category: "Building Society", trustRating: 3, description: "Dudley Building Society is a small mutual lender offering standard and specialist mortgage products." },
  { name: "Melton Building Society", slug: "melton", estimatedSvr: 8.49, maxLtv: 80, category: "Building Society", trustRating: 3, description: "Melton Building Society provides residential mortgage products with a personal approach." },
  { name: "Mansfield Building Society", slug: "mansfield", estimatedSvr: 7.99, maxLtv: 90, category: "Building Society", trustRating: 3, description: "Mansfield Building Society offers specialist mortgage products including self-build and agricultural properties." },
  { name: "The Mortgage Works", slug: "tmw", estimatedSvr: 7.99, maxLtv: 80, category: "Buy to Let", trustRating: 4, description: "The Mortgage Works (TMW), part of Nationwide, is a leading buy-to-let and let-to-buy mortgage lender." },
  { name: "Precise Mortgages", slug: "precise", estimatedSvr: 8.49, maxLtv: 85, category: "Specialist", trustRating: 4, description: "Precise Mortgages offers specialist mortgage products for complex cases including adverse credit." },
  { name: "Kensington Mortgages", slug: "kensington", estimatedSvr: 8.99, maxLtv: 85, category: "Specialist", trustRating: 3, description: "Kensington Mortgages specialises in products for borrowers who don't fit standard lending criteria." },
  { name: "Pepper Money", slug: "pepper", estimatedSvr: 9.49, maxLtv: 85, category: "Specialist", trustRating: 3, description: "Pepper Money is a specialist lender offering mortgages for those with adverse credit or complex income." },
  { name: "Foundation Home Loans", slug: "foundation", estimatedSvr: 8.99, maxLtv: 85, category: "Specialist", trustRating: 3, description: "Foundation Home Loans provides specialist buy-to-let and residential mortgage products." },
  { name: "Fleet Mortgages", slug: "fleet", estimatedSvr: 8.49, maxLtv: 80, category: "Buy to Let", trustRating: 3, description: "Fleet Mortgages is a specialist buy-to-let lender offering products for individual landlords and portfolio cases." },
  { name: "Landbay", slug: "landbay", estimatedSvr: 8.49, maxLtv: 80, category: "Buy to Let", trustRating: 4, description: "Landbay is a technology-driven buy-to-let lender with competitive rates and fast decisions." },
  { name: "Paragon Bank", slug: "paragon", estimatedSvr: 8.49, maxLtv: 80, category: "Buy to Let", trustRating: 4, description: "Paragon Bank is one of the UK's largest specialist buy-to-let mortgage lenders." },
  { name: "Aldermore Bank", slug: "aldermore", estimatedSvr: 8.99, maxLtv: 90, category: "Specialist", trustRating: 3, description: "Aldermore Bank offers residential and buy-to-let mortgages for those with complex financial situations." },
  { name: "Shawbrook Bank", slug: "shawbrook", estimatedSvr: 8.99, maxLtv: 80, category: "Specialist", trustRating: 3, description: "Shawbrook Bank provides specialist residential and buy-to-let mortgage products through brokers." },
  { name: "Metro Bank", slug: "metro-bank", estimatedSvr: 7.99, maxLtv: 90, category: "High Street", trustRating: 3, description: "Metro Bank offers residential mortgages with a focus on manual underwriting for complex cases." },
  { name: "Co-operative Bank", slug: "co-op", estimatedSvr: 7.99, maxLtv: 90, category: "High Street", trustRating: 3, description: "The Co-operative Bank offers ethical banking including competitive mortgage products." },
  { name: "Atom Bank", slug: "atom-bank", estimatedSvr: 7.99, maxLtv: 95, category: "Digital", trustRating: 4, description: "Atom Bank is a UK digital bank offering competitive fixed-rate mortgages exclusively through brokers." },
  { name: "Perenna", slug: "perenna", estimatedSvr: 7.49, maxLtv: 95, category: "Digital", trustRating: 4, description: "Perenna offers innovative long-term fixed rate mortgages up to 30 years for UK homebuyers." },
  { name: "Habito", slug: "habito", estimatedSvr: 7.99, maxLtv: 90, category: "Digital", trustRating: 3, description: "Habito is a digital mortgage broker and lender offering long-term fixed rate mortgage products." },
  { name: "Generation Home", slug: "gen-h", estimatedSvr: 7.99, maxLtv: 95, category: "Digital", trustRating: 4, description: "Generation Home offers innovative mortgages allowing family members to boost a buyer's deposit and income." },
  { name: "Mojo Mortgages", slug: "mojo", estimatedSvr: 7.99, maxLtv: 90, category: "Digital", trustRating: 3, description: "Mojo is a digital mortgage broker helping buyers find and apply for the best mortgage deals online." },
  { name: "Accord Mortgages", slug: "accord", estimatedSvr: 7.99, maxLtv: 95, category: "Building Society", trustRating: 4, description: "Accord Mortgages, part of Yorkshire Building Society, offers residential and buy-to-let products via brokers." },
  { name: "BM Solutions", slug: "bm-solutions", estimatedSvr: 7.99, maxLtv: 80, category: "Buy to Let", trustRating: 4, description: "BM Solutions, part of Lloyds Banking Group, is one of the UK's largest buy-to-let mortgage lenders." },
  { name: "Clydesdale Bank", slug: "clydesdale", estimatedSvr: 7.49, maxLtv: 95, category: "High Street", trustRating: 3, description: "Clydesdale Bank, part of Virgin Money, offers mortgage products in Scotland and across the UK." },
  { name: "Danske Bank UK", slug: "danske", estimatedSvr: 7.49, maxLtv: 90, category: "High Street", trustRating: 4, description: "Danske Bank UK provides mortgage products primarily in Northern Ireland with competitive fixed rates." },
  { name: "Bank of Ireland UK", slug: "boi", estimatedSvr: 7.74, maxLtv: 95, category: "High Street", trustRating: 3, description: "Bank of Ireland UK provides mortgage products in Northern Ireland and Great Britain." },
  { name: "Post Office Money", slug: "post-office", estimatedSvr: 7.99, maxLtv: 90, category: "High Street", trustRating: 3, description: "Post Office Money offers residential mortgage products through its UK-wide network." },
  { name: "Scottish Widows Bank", slug: "scottish-widows", estimatedSvr: 7.49, maxLtv: 95, category: "High Street", trustRating: 4, description: "Scottish Widows Bank, part of Lloyds Banking Group, provides competitive residential mortgage products." },
  { name: "Standard Life Home Finance", slug: "standard-life", estimatedSvr: 7.99, maxLtv: 60, category: "Equity Release", trustRating: 4, description: "Standard Life Home Finance offers equity release and lifetime mortgage products for over-55s." },
  { name: "First Direct", slug: "first-direct", estimatedSvr: 7.49, maxLtv: 90, category: "Digital", trustRating: 5, description: "First Direct, part of HSBC, is consistently rated the UK's best bank for customer service and offers competitive mortgages." },
  { name: "Platform", slug: "platform", estimatedSvr: 7.99, maxLtv: 95, category: "High Street", trustRating: 3, description: "Platform, part of the Co-operative Bank, offers competitive residential and remortgage products." },
  { name: "Godiva Mortgages", slug: "godiva", estimatedSvr: 7.49, maxLtv: 95, category: "Building Society", trustRating: 4, description: "Godiva Mortgages, part of Coventry Building Society, offers competitive mortgage products through brokers." },
  { name: "Family Building Society", slug: "family-bs", estimatedSvr: 7.99, maxLtv: 95, category: "Building Society", trustRating: 4, description: "Family Building Society specialises in helping families support younger buyers through Joint Borrower Sole Proprietor mortgages." },
  { name: "Leek United Building Society", slug: "leek-united", estimatedSvr: 7.99, maxLtv: 90, category: "Building Society", trustRating: 3, description: "Leek United Building Society offers residential mortgage products in England and Wales." },
  { name: "Furness Building Society", slug: "furness", estimatedSvr: 7.99, maxLtv: 90, category: "Building Society", trustRating: 3, description: "Furness Building Society is a mutual lender in the Lake District offering competitive residential mortgages." },
  { name: "Newbury Building Society", slug: "newbury", estimatedSvr: 7.99, maxLtv: 90, category: "Building Society", trustRating: 3, description: "Newbury Building Society provides flexible mortgage products for residential buyers in England." },
  { name: "Hinckley and Rugby Building Society", slug: "hinckley-rugby", estimatedSvr: 8.49, maxLtv: 90, category: "Building Society", trustRating: 3, description: "Hinckley and Rugby Building Society offers residential mortgages with a personal service." },
  { name: "Loughborough Building Society", slug: "loughborough", estimatedSvr: 7.99, maxLtv: 85, category: "Building Society", trustRating: 3, description: "Loughborough Building Society offers flexible residential mortgage products for standard and complex cases." },
  { name: "Tipton Building Society", slug: "tipton", estimatedSvr: 8.49, maxLtv: 85, category: "Building Society", trustRating: 3, description: "Tipton and Coseley Building Society provides residential mortgage products in the West Midlands and beyond." },
  { name: "Market Harborough Building Society", slug: "market-harborough", estimatedSvr: 8.49, maxLtv: 80, category: "Building Society", trustRating: 3, description: "Market Harborough Building Society offers flexible residential mortgage products for standard cases." },
  { name: "Saffron Building Society", slug: "saffron", estimatedSvr: 7.99, maxLtv: 90, category: "Building Society", trustRating: 3, description: "Saffron Building Society provides mortgage products for residential buyers and self-builders in East Anglia." },
  { name: "Teachers Building Society", slug: "teachers", estimatedSvr: 7.99, maxLtv: 95, category: "Building Society", trustRating: 3, description: "Teachers Building Society specialises in mortgages for education professionals and other borrowers." },
  { name: "Penrith Building Society", slug: "penrith", estimatedSvr: 8.49, maxLtv: 80, category: "Building Society", trustRating: 3, description: "Penrith Building Society serves Cumbria and surrounding areas with residential mortgage products." },
  { name: "Monmouthshire Building Society", slug: "monmouthshire", estimatedSvr: 7.99, maxLtv: 90, category: "Building Society", trustRating: 3, description: "Monmouthshire Building Society offers residential mortgage products in Wales and the borders." },
  { name: "Scottish Building Society", slug: "scottish-bs", estimatedSvr: 7.99, maxLtv: 85, category: "Building Society", trustRating: 3, description: "Scottish Building Society is Scotland's only independent building society, offering mortgage products north of the border." },
  { name: "Hodge Bank", slug: "hodge", estimatedSvr: 8.99, maxLtv: 75, category: "Specialist", trustRating: 3, description: "Hodge Bank specialises in mortgages for those aged 55 and over, including retirement interest-only products." },
  { name: "Together Money", slug: "together", estimatedSvr: 9.49, maxLtv: 85, category: "Specialist", trustRating: 3, description: "Together Money offers specialist mortgages for complex cases including unusual properties and adverse credit." },
  { name: "United Trust Bank", slug: "united-trust", estimatedSvr: 8.99, maxLtv: 80, category: "Specialist", trustRating: 3, description: "United Trust Bank provides specialist bridging loans and development finance alongside residential mortgages." },
  { name: "West One Loans", slug: "west-one", estimatedSvr: 9.49, maxLtv: 80, category: "Specialist", trustRating: 3, description: "West One Loans offers specialist bridging finance and buy-to-let mortgage products." },
  { name: "Spring Finance", slug: "spring-finance", estimatedSvr: 9.99, maxLtv: 75, category: "Specialist", trustRating: 2, description: "Spring Finance provides second charge mortgage products and bridging loans for homeowners." },
  { name: "Masthaven Bank", slug: "masthaven", estimatedSvr: 9.49, maxLtv: 80, category: "Specialist", trustRating: 3, description: "Masthaven Bank offers specialist mortgage products including bridging and complex residential cases." },
  { name: "Ipswich Building Society", slug: "ipswich", estimatedSvr: 7.99, maxLtv: 90, category: "Building Society", trustRating: 3, description: "Ipswich Building Society provides residential mortgage products in East Anglia and beyond." },
  { name: "Earl Shilton Building Society", slug: "earl-shilton", estimatedSvr: 8.99, maxLtv: 80, category: "Building Society", trustRating: 3, description: "Earl Shilton Building Society is a small mutual lender in Leicestershire offering residential mortgages." },
  { name: "Holmesdale Building Society", slug: "holmesdale", estimatedSvr: 8.99, maxLtv: 80, category: "Building Society", trustRating: 3, description: "Holmesdale Building Society is a small mutual lender in Surrey offering residential mortgage products." },
  { name: "Progressive Building Society", slug: "progressive", estimatedSvr: 7.99, maxLtv: 90, category: "Building Society", trustRating: 3, description: "Progressive Building Society is Northern Ireland's largest building society, offering competitive mortgage products." },
  { name: "Vernon Building Society", slug: "vernon", estimatedSvr: 7.99, maxLtv: 85, category: "Building Society", trustRating: 3, description: "Vernon Building Society is a small mutual lender in Stockport offering residential mortgage products." },
  { name: "Ecology Building Society", slug: "ecology", estimatedSvr: 7.49, maxLtv: 90, category: "Building Society", trustRating: 4, description: "Ecology Building Society specialises in mortgages for eco-friendly homes and sustainable building projects." },
  { name: "Chorley Building Society", slug: "chorley", estimatedSvr: 8.49, maxLtv: 85, category: "Building Society", trustRating: 3, description: "Chorley Building Society offers residential mortgage products in Lancashire and surrounding areas." },
  { name: "Darlington Building Society", slug: "darlington", estimatedSvr: 7.99, maxLtv: 90, category: "Building Society", trustRating: 3, description: "Darlington Building Society provides residential mortgages in the North East and Yorkshire." },
  { name: "Harpenden Building Society", slug: "harpenden", estimatedSvr: 8.49, maxLtv: 85, category: "Building Society", trustRating: 3, description: "Harpenden Building Society is a small mutual lender in Hertfordshire offering residential mortgages." },
  { name: "Ipswich and Suffolk", slug: "ipswich-suffolk", estimatedSvr: 7.99, maxLtv: 90, category: "Building Society", trustRating: 3, description: "Ipswich and Suffolk offers mortgage products in East Anglia through a mutual building society model." },
  { name: "Kent Reliance", slug: "kent-reliance", estimatedSvr: 8.99, maxLtv: 85, category: "Specialist", trustRating: 3, description: "Kent Reliance, part of OneSavings Bank, is a specialist lender for complex residential and buy-to-let cases." },
  { name: "OneSavings Bank", slug: "onesavings", estimatedSvr: 8.99, maxLtv: 85, category: "Specialist", trustRating: 3, description: "OneSavings Bank provides specialist mortgage products under the Kent Reliance and InterBay brands." },
  { name: "Bluestone Mortgages", slug: "bluestone", estimatedSvr: 9.49, maxLtv: 85, category: "Specialist", trustRating: 3, description: "Bluestone Mortgages specialises in near-prime mortgages for those with minor adverse credit history." },
  { name: "Vida Homeloans", slug: "vida", estimatedSvr: 9.49, maxLtv: 85, category: "Specialist", trustRating: 3, description: "Vida Homeloans offers specialist residential and buy-to-let mortgages for complex borrower profiles." },
  { name: "Zephyr Homeloans", slug: "zephyr", estimatedSvr: 8.99, maxLtv: 80, category: "Buy to Let", trustRating: 3, description: "Zephyr Homeloans is a specialist buy-to-let lender offering products for individual and portfolio landlords." },
  { name: "LendInvest", slug: "lendinvest", estimatedSvr: 8.99, maxLtv: 80, category: "Buy to Let", trustRating: 3, description: "LendInvest offers buy-to-let and bridging mortgage products with competitive rates for landlords." },
  { name: "Octane Capital", slug: "octane", estimatedSvr: 9.49, maxLtv: 80, category: "Specialist", trustRating: 3, description: "Octane Capital provides bridging finance and specialist mortgage products for property investors." },
  { name: "Precise Mortgages", slug: "precise-btl", estimatedSvr: 8.49, maxLtv: 80, category: "Buy to Let", trustRating: 3, description: "Precise Mortgages offers specialist buy-to-let products for HMOs, multi-unit blocks, and portfolio landlords." },
  { name: "Nationwide Mortgage", slug: "nationwide-remortgage", estimatedSvr: 7.49, maxLtv: 90, category: "Remortgage", trustRating: 5, description: "Nationwide offers some of the UK's most competitive remortgage deals with fee-free options and cashback." },
  { name: "Halifax Remortgage", slug: "halifax-remortgage", estimatedSvr: 7.49, maxLtv: 90, category: "Remortgage", trustRating: 5, description: "Halifax offers competitive remortgage products with free legal work and no valuation fees." },
  { name: "Barclays Remortgage", slug: "barclays-remortgage", estimatedSvr: 7.49, maxLtv: 90, category: "Remortgage", trustRating: 5, description: "Barclays offers competitive remortgage deals with a range of fixed and tracker rate products." },
  { name: "NatWest Remortgage", slug: "natwest-remortgage", estimatedSvr: 7.49, maxLtv: 90, category: "Remortgage", trustRating: 5, description: "NatWest provides competitive remortgage products with a straightforward switching process." },
  { name: "HSBC Remortgage", slug: "hsbc-remortgage", estimatedSvr: 6.99, maxLtv: 85, category: "Remortgage", trustRating: 5, description: "HSBC offers some of the UK's lowest remortgage rates, especially for borrowers with high equity." },
  { name: "Santander Remortgage", slug: "santander-remortgage", estimatedSvr: 7.5, maxLtv: 90, category: "Remortgage", trustRating: 4, description: "Santander offers competitive remortgage deals for home movers and those switching from other lenders." },
  { name: "April Mortgages", slug: "april", estimatedSvr: 7.49, maxLtv: 90, category: "Digital", trustRating: 4, description: "April Mortgages offers long-term fixed rate mortgages designed to give homeowners certainty for up to 15 years." },
  { name: "Tembo Money", slug: "tembo", estimatedSvr: 7.99, maxLtv: 95, category: "Digital", trustRating: 4, description: "Tembo offers innovative mortgage products including Income Boost and Deposit Boost to help first-time buyers." },
  { name: "Proportunity", slug: "proportunity", estimatedSvr: 7.99, maxLtv: 90, category: "Digital", trustRating: 3, description: "Proportunity uses AI to offer equity loans that boost buyers' deposits, helping more people onto the property ladder." },
  { name: "Quantum Mortgages", slug: "quantum", estimatedSvr: 8.49, maxLtv: 85, category: "Specialist", trustRating: 3, description: "Quantum Mortgages offers specialist residential and buy-to-let products via brokers." },
  { name: "InterBay Commercial", slug: "interbay", estimatedSvr: 8.99, maxLtv: 80, category: "Specialist", trustRating: 3, description: "InterBay Commercial provides specialist commercial and semi-commercial mortgage products." },
  { name: "Castle Trust Bank", slug: "castle-trust", estimatedSvr: 8.49, maxLtv: 80, category: "Specialist", trustRating: 3, description: "Castle Trust Bank offers specialist bridging finance and buy-to-let mortgage products for investors." },
  { name: "Gatehouse Bank", slug: "gatehouse", estimatedSvr: 7.99, maxLtv: 80, category: "Specialist", trustRating: 3, description: "Gatehouse Bank offers Sharia-compliant home purchase plans as an ethical alternative to conventional mortgages." },
  { name: "Ahli United Bank", slug: "ahli-united", estimatedSvr: 7.99, maxLtv: 80, category: "Specialist", trustRating: 3, description: "Ahli United Bank provides Sharia-compliant home finance products for UK Muslims." },
  { name: "Al Rayan Bank", slug: "al-rayan", estimatedSvr: 7.49, maxLtv: 85, category: "Specialist", trustRating: 4, description: "Al Rayan Bank is the UK's largest Islamic bank, offering Sharia-compliant home purchase plans." },
  { name: "Buckinghamshire BS", slug: "bucks-remortgage", estimatedSvr: 8.49, maxLtv: 80, category: "Remortgage", trustRating: 3, description: "Buckinghamshire Building Society offers flexible remortgage products for existing homeowners." },
  { name: "Penrith Building Society", slug: "penrith-remortgage", estimatedSvr: 8.49, maxLtv: 80, category: "Remortgage", trustRating: 3, description: "Penrith Building Society provides remortgage products for borrowers in Cumbria and nationally." },
  { name: "TSB", slug: "tsb", maxLtv: 90, estimatedSvr: 7.99, description: "TSB Bank mortgage products", trustRating: 4 },
  { name: "Clydesdale Bank", slug: "clydesdale", maxLtv: 90, estimatedSvr: 7.74, description: "Clydesdale Bank mortgage products", trustRating: 4 },
  { name: "Bank of Ireland", slug: "bank-of-ireland", maxLtv: 90, estimatedSvr: 7.50, description: "Bank of Ireland UK mortgage products", trustRating: 4 },
  { name: "Marsden Building Society", slug: "marsden", maxLtv: 85, estimatedSvr: 7.24, description: "Marsden Building Society mortgage products", trustRating: 4 },
  { name: "Furness Building Society", slug: "furness", maxLtv: 85, estimatedSvr: 7.49, description: "Furness Building Society mortgage products", trustRating: 4 },
  { name: "Tipton and Coseley", slug: "tipton", maxLtv: 85, estimatedSvr: 7.49, description: "Tipton & Coseley Building Society mortgage products", trustRating: 4 },
  { name: "Newbury Building Society", slug: "newbury", maxLtv: 80, estimatedSvr: 7.24, description: "Newbury Building Society mortgage products", trustRating: 4 },
  { name: "Hanley Economic", slug: "hanley-economic", maxLtv: 80, estimatedSvr: 7.24, description: "Hanley Economic Building Society mortgage products", trustRating: 4 },
  { name: "Melton Building Society", slug: "melton", maxLtv: 85, estimatedSvr: 7.49, description: "Melton Building Society mortgage products", trustRating: 4 },
  { name: "Saffron Building Society", slug: "saffron", maxLtv: 85, estimatedSvr: 7.24, description: "Saffron Building Society mortgage products", trustRating: 4 },
  { name: "Harpenden Building Society", slug: "harpenden", maxLtv: 80, estimatedSvr: 7.24, description: "Harpenden Building Society mortgage products", trustRating: 4 },
  { name: "Market Harborough", slug: "market-harborough", maxLtv: 80, estimatedSvr: 7.24, description: "Market Harborough Building Society mortgage products", trustRating: 4 },
  { name: "Chorley Building Society", slug: "chorley", maxLtv: 80, estimatedSvr: 7.49, description: "Chorley Building Society mortgage products", trustRating: 4 },
  { name: "Loughborough Building Society", slug: "loughborough", maxLtv: 85, estimatedSvr: 7.24, description: "Loughborough Building Society mortgage products", trustRating: 4 },
  { name: "Mansfield Building Society", slug: "mansfield", maxLtv: 85, estimatedSvr: 7.49, description: "Mansfield Building Society mortgage products", trustRating: 4 },
  { name: "Monmouthshire Building Society", slug: "monmouthshire", maxLtv: 80, estimatedSvr: 7.24, description: "Monmouthshire Building Society mortgage products", trustRating: 4 },
  { name: "Swansea Building Society", slug: "swansea-bs", maxLtv: 80, estimatedSvr: 7.24, description: "Swansea Building Society mortgage products", trustRating: 4 },
  { name: "Ecology Building Society", slug: "ecology", maxLtv: 80, estimatedSvr: 7.74, description: "Ecology Building Society — green mortgage specialist", trustRating: 4 },
  { name: "Zephyr Homeloans", slug: "zephyr", maxLtv: 80, estimatedSvr: 7.99, description: "Zephyr Homeloans buy-to-let specialist", trustRating: 4 },
  { name: "Kent Reliance", slug: "kent-reliance", maxLtv: 85, estimatedSvr: 8.24, description: "Kent Reliance specialist mortgage lender", trustRating: 4 },
  { name: "Together Money", slug: "together", maxLtv: 75, estimatedSvr: 9.49, description: "Together Money specialist and bridging lender", trustRating: 3 },
  { name: "Octane Capital", slug: "octane", maxLtv: 75, estimatedSvr: 9.99, description: "Octane Capital bridging and development finance", trustRating: 3 },
  { name: "United Trust Bank", slug: "united-trust", maxLtv: 75, estimatedSvr: 8.99, description: "United Trust Bank specialist mortgage products", trustRating: 4 },
  { name: "Castle Trust", slug: "castle-trust", maxLtv: 80, estimatedSvr: 8.74, description: "Castle Trust Bank mortgage products", trustRating: 4 },
  { name: "Vida Homeloans", slug: "vida", maxLtv: 85, estimatedSvr: 8.24, description: "Vida Homeloans specialist mortgage lender", trustRating: 4 },
  { name: "Dudley Building Society", slug: "dudley", maxLtv: 80, estimatedSvr: 7.24, description: "Dudley Building Society mortgage products", trustRating: 4 },
  { name: "Cambridge Building Society", slug: "cambridge-bs", maxLtv: 85, estimatedSvr: 7.24, description: "Cambridge Building Society mortgage products", trustRating: 4 },
  { name: "National Counties Building Society", slug: "national-counties", maxLtv: 80, estimatedSvr: 7.49, description: "National Counties Building Society mortgage products", trustRating: 4 },
  { name: "Earl Shilton Building Society", slug: "earl-shilton", maxLtv: 80, estimatedSvr: 7.24, description: "Earl Shilton Building Society mortgage products", trustRating: 4 },
  { name: "Stafford Railway Building Society", slug: "stafford-railway", maxLtv: 75, estimatedSvr: 7.24, description: "Stafford Railway Building Society mortgage products", trustRating: 4 },
  { name: "Newcastle Building Society", slug: "newcastle-bs", maxLtv: 85, estimatedSvr: 7.49, description: "Newcastle Building Society mortgage products", trustRating: 4 },
  { name: "Darlington Building Society", slug: "darlington", maxLtv: 80, estimatedSvr: 7.24, description: "Darlington Building Society mortgage products", trustRating: 4 },
  { name: "Ipswich Building Society", slug: "ipswich-bs", maxLtv: 80, estimatedSvr: 7.49, description: "Ipswich Building Society mortgage products", trustRating: 4 },
  { name: "Suffolk Building Society", slug: "suffolk", maxLtv: 80, estimatedSvr: 7.24, description: "Suffolk Building Society mortgage products", trustRating: 4 },
  { name: "Scottish Building Society", slug: "scottish-bs", maxLtv: 80, estimatedSvr: 7.24, description: "Scottish Building Society mortgage products", trustRating: 4 },
  { name: "Hinckley and Rugby", slug: "hinckley-rugby", maxLtv: 85, estimatedSvr: 7.49, description: "Hinckley & Rugby Building Society mortgage products", trustRating: 4 },
  { name: "Principality Building Society", slug: "principality", maxLtv: 85, estimatedSvr: 7.49, description: "Principality Building Society Wales mortgage products", trustRating: 4 },
  { name: "Generation Home", slug: "generation-home", maxLtv: 95, estimatedSvr: 7.24, description: "Generation Home income booster and family mortgage specialist", trustRating: 5 },
  { name: "Tembo", slug: "tembo", maxLtv: 95, estimatedSvr: 7.49, description: "Tembo family mortgage and deposit boost specialist", trustRating: 5 },
  { name: "Perenna", slug: "perenna", maxLtv: 90, estimatedSvr: 6.99, description: "Perenna long-term fixed rate mortgage specialist", trustRating: 5 },

];

export function getLenderBySlug(slug: string): LenderData | undefined {
  return lenders.find((l) => l.slug === slug);
}

export function buildLenderPath(type: string, slug: string): string {
  return `/calculators/${type}/${slug}`;
}

export function buildLenderGuidePath(slug: string): string {
  return `/guides/lenders/${slug}`;
}
