export interface LenderData {
  name: string;
  slug: string;
  estimatedSvr: number;
  maxLtv: number;
  category: string;
  trustRating: number;
  description: string;
}

export const lenders: LenderData[] = [
  { name: "Lloyds Bank", slug: "lloyds-bank", estimatedSvr: 7.5, maxLtv: 95, category: "Big Six", trustRating: 4.8, description: "One of the UK's largest mortgage lenders with over 300 years of banking history. Lloyds offers a wide range of residential and buy-to-let products, often with competitive fixed-rate deals for first-time buyers and home movers. As part of the Lloyds Banking Group, it also owns Halifax and Scottish Widows." },
  { name: "Halifax", slug: "halifax", estimatedSvr: 7.73, maxLtv: 95, category: "Big Six", trustRating: 4.7, description: "The UK's largest mortgage lender by volume. Halifax is known for accessible high-LTV products and its long track record with first-time buyers. Part of the Lloyds Banking Group, Halifax regularly features in best-buy tables for both purchase and remortgage deals." },
  { name: "Nationwide Building Society", slug: "nationwide", estimatedSvr: 7.99, maxLtv: 95, category: "Big Six", trustRating: 4.9, description: "The world's largest building society, owned by its members rather than shareholders. Nationwide is widely regarded for transparent pricing, strong customer service, and competitive rates across fixed, tracker, and offset mortgage products." },
  { name: "Barclays", slug: "barclays", estimatedSvr: 7.74, maxLtv: 90, category: "Big Six", trustRating: 4.6, description: "A major UK high-street bank with a strong mortgage presence. Barclays offers a range of fixed and tracker products up to 90% LTV, with a focus on technology-driven applications and competitive rates for remortgaging customers." },
  { name: "HSBC UK", slug: "hsbc", estimatedSvr: 6.99, maxLtv: 90, category: "Big Six", trustRating: 4.5, description: "The UK arm of the global banking giant, known for some of the most competitive SVR and fixed rates in the market. HSBC offers both residential and buy-to-let products and is a popular choice for higher-value properties and international buyers." },
  { name: "NatWest", slug: "natwest", estimatedSvr: 7.74, maxLtv: 95, category: "Big Six", trustRating: 4.6, description: "Part of the NatWest Group alongside RBS and Ulster Bank. NatWest offers comprehensive residential mortgage products including high-LTV options for first-time buyers, green mortgages for energy-efficient homes, and specialist support for shared ownership." },
  { name: "Santander UK", slug: "santander", estimatedSvr: 7.5, maxLtv: 95, category: "Major", trustRating: 4.6, description: "A major UK lender with Spanish parent group Banco Santander. Known for competitive fixed-rate deals, Santander offers products up to 95% LTV and has a strong intermediary presence. Their 123 mortgage has been a popular product for existing Santander current account holders." },
  { name: "Virgin Money", slug: "virgin-money", estimatedSvr: 8.24, maxLtv: 90, category: "Major", trustRating: 4.3, description: "Formed from the merger of Virgin Money and Clydesdale Bank under the Virgin Money UK brand. Known for distinctive branding and digital-first approach, Virgin Money offers residential and buy-to-let mortgages with regular competitive fixed-rate promotions." },
  { name: "TSB Bank", slug: "tsb", estimatedSvr: 7.74, maxLtv: 95, category: "Major", trustRating: 4.2, description: "Relaunched in 2013 from the former Lloyds TSB, now owned by Spanish bank Sabadell. TSB positions itself as a straightforward high-street lender with competitive rates for first-time buyers and home movers, offering products up to 95% LTV." },
  { name: "Coventry Building Society", slug: "coventry", estimatedSvr: 7.49, maxLtv: 90, category: "Building Society", trustRating: 4.8, description: "The UK's second-largest building society by assets. Coventry is consistently rated among the top societies for customer satisfaction and frequently offers market-leading fixed rates. Known for straightforward products without complex fee structures." },
  { name: "Yorkshire Building Society", slug: "yorkshire", estimatedSvr: 7.74, maxLtv: 90, category: "Building Society", trustRating: 4.7, description: "One of the UK's largest building societies, based in Bradford. Yorkshire BS offers a range of residential mortgages and is particularly strong in the intermediary market through its subsidiaries Accord Mortgages and Chelsea Building Society." },
  { name: "Skipton Building Society", slug: "skipton", estimatedSvr: 6.79, maxLtv: 90, category: "Building Society", trustRating: 4.8, description: "Based in North Yorkshire, Skipton is known for innovation in the mortgage market. It was one of the first lenders to offer a 100% mortgage product for renters without a deposit, and consistently delivers competitive SVR and fixed rates." },
  { name: "Leeds Building Society", slug: "leeds", estimatedSvr: 7.74, maxLtv: 95, category: "Building Society", trustRating: 4.6, description: "The fifth-largest building society in the UK. Leeds BS offers mortgages up to 95% LTV and is known for lending on non-standard construction types and shared ownership properties where other lenders may not." },
  { name: "Principality Building Society", slug: "principality", estimatedSvr: 7.5, maxLtv: 90, category: "Regional", trustRating: 4.5, description: "The largest building society in Wales, headquartered in Cardiff. Principality has deep roots in the Welsh property market and offers residential, buy-to-let, and shared ownership mortgages with a strong focus on local communities." },
  { name: "Newcastle Building Society", slug: "newcastle", estimatedSvr: 7.69, maxLtv: 95, category: "Regional", trustRating: 4.4, description: "A well-established North East building society offering competitive mortgage products. Newcastle BS is known for supporting first-time buyers with high-LTV products and for lending on properties in areas some national lenders avoid." },
  { name: "Nottingham Building Society", slug: "nottingham", estimatedSvr: 7.5, maxLtv: 95, category: "Regional", trustRating: 4.3, description: "An East Midlands building society with a growing national intermediary presence. Nottingham BS offers residential and buy-to-let products up to 95% LTV, with a reputation for pragmatic underwriting and accessible customer service." },
  { name: "West Bromwich Building Society", slug: "west-brom", estimatedSvr: 8.19, maxLtv: 90, category: "Regional", trustRating: 4.2, description: "A West Midlands-based building society serving the region since 1849. West Brom offers residential and buy-to-let mortgage products and has a niche presence in the later-life lending market with equity release products." },
  { name: "Cumberland Building Society", slug: "cumberland", estimatedSvr: 7.24, maxLtv: 90, category: "Regional", trustRating: 4.7, description: "Headquartered in Carlisle, Cumberland is a respected regional building society covering Cumbria and south-west Scotland. Known for competitive rates, personal service, and flexibility in assessing mortgage applications for rural properties." },
  { name: "Suffolk Building Society", slug: "suffolk", estimatedSvr: 7.74, maxLtv: 90, category: "Regional", trustRating: 4.5, description: "A community-focused building society operating primarily in East Anglia. Suffolk BS offers straightforward residential mortgage products with personal underwriting, and is known for considering applications that may not fit high-street lender criteria." },
  { name: "Cambridge Building Society", slug: "cambridge", estimatedSvr: 7.19, maxLtv: 90, category: "Regional", trustRating: 4.6, description: "Based in Cambridgeshire, this mutual building society offers competitive residential mortgages with a personal approach. Cambridge BS is known for pragmatic lending decisions and has a strong reputation in one of the UK's most dynamic property markets." },
  { name: "Bath Building Society", slug: "bath", estimatedSvr: 7.2, maxLtv: 95, category: "Boutique", trustRating: 4.5, description: "A small but well-regarded building society in Bath. Bath BS offers residential mortgages up to 95% LTV and is known for manual underwriting, meaning it considers applications individually rather than through automated scoring systems." },
  { name: "Buckinghamshire Building Society", slug: "bucks", estimatedSvr: 7.49, maxLtv: 90, category: "Boutique", trustRating: 4.4, description: "A small, specialist building society based in Buckinghamshire. Known for competitive buy-to-let and residential products, Bucks BS offers personal underwriting and considers applications from self-employed borrowers and those with complex income." },
  { name: "Dudley Building Society", slug: "dudley", estimatedSvr: 7.74, maxLtv: 90, category: "Boutique", trustRating: 4.3, description: "A community building society rooted in the West Midlands Black Country. Dudley BS offers residential mortgages with a personal touch, and is known for considering non-standard income types and lending on properties other lenders may decline." },
  { name: "Melton Mowbray Building Society", slug: "melton", estimatedSvr: 7.99, maxLtv: 90, category: "Boutique", trustRating: 4.2, description: "Based in the Leicestershire market town of Melton Mowbray, this boutique building society offers residential mortgages with flexible underwriting criteria. Known for competitive rates in the East Midlands property market." },
  { name: "Mansfield Building Society", slug: "mansfield", estimatedSvr: 7.5, maxLtv: 95, category: "Boutique", trustRating: 4.3, description: "A Nottinghamshire-based building society offering residential mortgages up to 95% LTV. Mansfield BS is known for supporting first-time buyers and for considering applications from borrowers with non-standard credit histories." },
  { name: "The Mortgage Works", slug: "tmw", estimatedSvr: 7.74, maxLtv: 80, category: "Specialist", trustRating: 4.4, description: "A specialist buy-to-let lender owned by Nationwide Building Society. TMW is one of the largest BTL lenders in the UK market, available exclusively through mortgage intermediaries, and known for competitive rates on portfolio landlord products." },
  { name: "Precise Mortgages", slug: "precise", estimatedSvr: 8.25, maxLtv: 85, category: "Specialist", trustRating: 4.1, description: "A specialist lender within the Charter Court Financial Services group, focused on borrowers who do not fit mainstream criteria. Precise offers products for self-employed, contractors, and borrowers with adverse credit histories." },
  { name: "Kensington Mortgages", slug: "kensington", estimatedSvr: 8.49, maxLtv: 85, category: "Specialist", trustRating: 4.0, description: "A specialist lender that focuses on borrowers underserved by the mainstream market. Kensington is known for considering complex employment income, self-employment, and near-prime credit profiles where high-street banks may not lend." },
  { name: "Pepper Money", slug: "pepper", estimatedSvr: 8.74, maxLtv: 85, category: "Specialist", trustRating: 3.9, description: "A specialist lender offering products for borrowers with complex income or credit situations. Pepper Money is known for manual underwriting and flexibility with self-employed applicants, contract workers, and those with historic credit issues." },
  { name: "Foundation Home Loans", slug: "foundation", estimatedSvr: 8.24, maxLtv: 80, category: "Specialist", trustRating: 4.1, description: "A specialist buy-to-let and residential lender focused on professional landlords and borrowers with complex income. Foundation is known for competitive BTL products and pragmatic underwriting for self-employed and contract workers." },
  { name: "Fleet Mortgages", slug: "fleet", estimatedSvr: 7.74, maxLtv: 80, category: "Specialist", trustRating: 4.2, description: "A specialist buy-to-let lender known for serving portfolio landlords and limited company borrowers. Fleet offers competitive BTL products through intermediaries and is regarded for straightforward processing on complex portfolio cases." },
  { name: "Landbay", slug: "landbay", estimatedSvr: 7.49, maxLtv: 80, category: "Specialist", trustRating: 4.3, description: "A technology-driven specialist BTL lender that uses automated decisioning for speed. Landbay is known for competitive buy-to-let rates, fast processing times, and support for portfolio landlords and limited company structures." },
  { name: "Paragon Bank", slug: "paragon", estimatedSvr: 7.75, maxLtv: 80, category: "Specialist", trustRating: 4.4, description: "One of the UK's largest specialist buy-to-let lenders with decades of experience in the landlord market. Paragon is known for expertise in complex BTL cases, portfolio lending, HMO mortgages, and professional landlord products." },
  { name: "Aldermore Bank", slug: "aldermore", estimatedSvr: 7.74, maxLtv: 90, category: "Challenger", trustRating: 4.2, description: "A challenger bank offering residential and buy-to-let mortgages for borrowers who may not fit mainstream criteria. Aldermore is known for pragmatic underwriting for self-employed applicants, contractors, and those with complex income streams." },
  { name: "Shawbrook Bank", slug: "shawbrook", estimatedSvr: 8.25, maxLtv: 85, category: "Challenger", trustRating: 4.3, description: "A challenger bank specialising in commercial and specialist residential lending. Shawbrook is known for bridging finance, development loans, and buy-to-let products for experienced landlords and property investors." },
  { name: "Metro Bank", slug: "metro-bank", estimatedSvr: 7.5, maxLtv: 95, category: "Challenger", trustRating: 4.1, description: "A UK challenger bank founded in 2010 as the first new high-street bank in over 100 years. Metro Bank offers residential mortgages up to 95% LTV and is known for its seven-day-a-week branch opening and accessible customer service." },
  { name: "Co-operative Bank", slug: "co-op", estimatedSvr: 7.74, maxLtv: 95, category: "Challenger", trustRating: 4.4, description: "An ethical banking pioneer offering residential mortgages with a values-driven approach. The Co-operative Bank is known for its ethical policy, green mortgage products, and competitive rates for both first-time buyers and home movers." },
  { name: "Atom Bank", slug: "atom-bank", estimatedSvr: 7.24, maxLtv: 90, category: "Challenger", trustRating: 4.6, description: "The UK's first app-only bank, based in Durham. Atom Bank offers competitive fixed-rate mortgage products entirely online, with a streamlined digital application process and consistently competitive pricing against high-street lenders." },
  { name: "Perenna", slug: "perenna", estimatedSvr: 5.75, maxLtv: 95, category: "Innovator", trustRating: 4.8, description: "A next-generation lender offering long-term fixed-rate mortgages inspired by continental European models. Perenna's products allow borrowers to lock in rates for the full mortgage term, providing payment certainty that traditional UK lenders typically do not offer." },
  { name: "Habito", slug: "habito", estimatedSvr: 6.5, maxLtv: 90, category: "Innovator", trustRating: 4.7, description: "A digital mortgage broker that also offers its own Habito One product — a long-term fixed-rate mortgage designed for borrowers who want rate certainty for up to 40 years. Known for a fully digital application journey and transparent fee structures." },
  { name: "Gen H", slug: "gen-h", estimatedSvr: 7.24, maxLtv: 95, category: "Innovator", trustRating: 4.9, description: "A purpose-built lender designed to help people get on the property ladder through income-boosting features. Gen H allows family or friends to contribute income to a mortgage application, addressing affordability barriers for first-time buyers." },
  { name: "Mojo Mortgages", slug: "mojo", estimatedSvr: 7.74, maxLtv: 95, category: "Innovator", trustRating: 4.6, description: "An online mortgage broker offering fee-free advice and a technology-driven comparison platform. Mojo Mortgages helps borrowers compare products across the market with a streamlined digital application process and human adviser support." },
  { name: "Accord Mortgages", slug: "accord", estimatedSvr: 7.74, maxLtv: 90, category: "Broker-Only", trustRating: 4.5, description: "The intermediary-only lending arm of Yorkshire Building Society. Accord is a major player in the broker market, offering competitive residential and buy-to-let products exclusively through mortgage advisers and intermediary networks." },
  { name: "BM Solutions", slug: "bm-solutions", estimatedSvr: 7.74, maxLtv: 75, category: "Broker-Only", trustRating: 4.4, description: "The intermediary-only buy-to-let lending brand of Lloyds Banking Group. BM Solutions is one of the UK's largest BTL lenders, offering products for individual and portfolio landlords exclusively through mortgage brokers." },
  { name: "Clydesdale Bank", slug: "clydesdale", estimatedSvr: 7.74, maxLtv: 90, category: "Regional", trustRating: 4.1, description: "A Scottish bank now part of the Virgin Money UK group. Clydesdale has deep roots in the Scottish property market and offers residential mortgages with competitive rates, particularly for properties in Scotland and Northern England." },
  { name: "Danske Bank", slug: "danske", estimatedSvr: 7.5, maxLtv: 90, category: "Regional", trustRating: 4.3, description: "The UK arm of the Danish banking group, primarily operating in Northern Ireland. Danske Bank is one of the largest mortgage lenders in Northern Ireland and offers residential and buy-to-let products tailored to the local property market." },
  { name: "Bank of Ireland UK", slug: "boi", estimatedSvr: 7.74, maxLtv: 90, category: "Regional", trustRating: 4.2, description: "The UK division of Bank of Ireland, operating across Northern Ireland and Great Britain. Known for competitive residential mortgage products and strong presence in the Northern Ireland property market through its branch network." },
  { name: "Post Office Money", slug: "post-office", estimatedSvr: 7.74, maxLtv: 90, category: "White-Label", trustRating: 4.4, description: "Mortgage products offered under the Post Office brand, underwritten by Bank of Ireland UK. Post Office Money provides residential mortgages through the familiar Post Office network, making mortgage access convenient at local branches." },
  { name: "Scottish Widows", slug: "scottish-widows", estimatedSvr: 7.74, maxLtv: 90, category: "Insurance-Led", trustRating: 4.5, description: "Part of the Lloyds Banking Group, Scottish Widows offers mortgage products alongside its well-known insurance and pensions business. Known for competitive remortgage deals and buy-to-let products available through intermediaries." },
  { name: "Standard Life", slug: "standard-life", estimatedSvr: 7.74, maxLtv: 90, category: "Insurance-Led", trustRating: 4.4, description: "A historic Scottish financial services brand now part of the Phoenix Group. Standard Life offers residential and buy-to-let mortgage products through intermediaries, leveraging its insurance heritage and strong brand recognition." },
];

export function getLenderBySlug(slug: string) {
  return lenders.find((lender) => lender.slug === slug);
}

export function buildLenderPath(
  calculator: "repayment" | "overpayment" | "max-borrowing",
  slug: string,
) {
  return `/calculators/${calculator}/${slug}`;
}

export function buildLenderGuidePath(slug: string) {
  return `/guides/lenders/${slug}`;
}
